const { PREFIX } = require("../../config");

module.exports = {
  name: "start",
  description: "Comando para startar o bot",
  commands: ["start", "iniciar"],
  usage: `${PREFIX}start`,
  handle: async ({ sendSuccessReply, sendReply, nickName }) => {
    await sendSuccessReply(`*⎋ ${nickName}! Olá e seja bem-vindo(a) ao bot Alucard! Antes de utilizar nossos serviços, gostaríamos que você desse uma atenção especial aos nossos Termos de Uso e Política de Privacidade. Nesse documento, detalhamos minuciosamente como suas informações serão tratadas e protegidas durante a interação com o bot Alucard. Ao prosseguir utilizando nossos serviços, você estará concordando plenamente com estes termos e condições. Caso haja alguma discordância, infelizmente não será possível usufruir dos recursos do bot.*\n\n*ᨏ TERMOS DE USO - Bot Alucard:*\n\n*҂ Alucard é um bot gratuito desenvolvido por estudantes da área da tecnologia. nosso objetivo é oferecer assistência nas suas buscas e estudos em diversas áreas, proporcionando uma experiência única sem qualquer cobrança financeira.*\n\n*1 - Consentimento do usuário: Ao utilizar o bot Alucard, você concorda com os seguintes termos e condições de uso. Caso não concorde com esses termos, não será possível utilizar os serviços do bot.*\n\n*2 - Uso dos dados: O bot Alucard não coleta, armazena nem utiliza os dados pessoais fornecidos pelos usuários. Sua prioridade é garantir a privacidade e segurança dos dados.*\n\n*3 - Limitações e responsabilidades: O bot Alucard se esforça para fornecer informações precisas e atualizadas. Contudo, ele não pode garantir a exatidão ou integridade das informações retornadas, uma vez que dependem de fontes externas. Os desenvolvedores não se responsabilizam por quaisquer consequências decorrentes do uso indevido das informações obtidas através do bot.*\n\n*4 - Propósito educacional: O Alucard é um projeto de cunho educacional, criado para fins de aprendizado e desenvolvimento de habilidades técnicas pelos desenvolvedores. Ele não possui fins lucrativos.*\n\n*5 - Modificações nos termos: Os desenvolvedores do Alucard reserva-se o direito de alterar estes termos de uso a qualquer momento. Quaisquer alterações serão comunicadas aos usuários e passarão a vigorar a partir da data de publicação.*\n\n*6 - Direitos do usuário: Os usuários têm o direito de acessar, retificar ou excluir seus dados pessoais. Para exercer esses direitos, basta entrar em contato com o suporte disponibilizado ou utilizar o comando /remocao diretamente no bot Alucard.*\n\n*7 - Proibição de uso indevido: O uso do Alucard para atividades ilegais, fraudulentas, ofensivas, ou que violem os direitos de terceiros é estritamente proibido e de responsabilidade do usuário.*
\n*8 - Propriedade intelectual: Todos os direitos de propriedade intelectual do bot Alucard e de suas funcionalidades pertencem aos desenvolvedores. É vedada qualquer reprodução ou uso não autorizado.*\n\n*9 - Segurança: Os desenvolvedores estão comprometidos em manter a segurança do bot Alucard. Caso identifique alguma vulnerabilidade ou problema de segurança, por favor, comunique ao suporte imediatamente.*\n\n*⎇ Estes termos de uso estão em conformidade com a Lei Geral de Proteção de Dados (LGPD) e têm como objetivo proteger a privacidade e os direitos dos usuários, proporcionando uma melhor experiência para todos.*`);
    await sendReply(`Entrem no canal de *Update do Alucard*.
Lá ocorrerá sorteios de contas premiums, e vocês vão ficar sabendo das últimas atualizações do bot.

https://chat.whatsapp.com/KXJzOE37McRA0XqD0N7UtL`);
  },
};
